[connections.supabase]
SUPABASE_URL = "https://hhpnagduugfuslatajxj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocG5hZ2R1dWdmdXNsYXRhanhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzQwMTUsImV4cCI6MjA1NjAxMDAxNX0.hHzulEjuh2SZvzBMcJPl-2YSGzaOf6qv_GtCHn3Z71c"